
services:
  - type: web
    name: appimgvid-backend2026
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AGNES_API_KEY
        sync: false
